# example netlify.toml
[build]
  command = "yarn build"
  functions = "functions"
  publish = "build"
  
  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/netlify-dev-plugin#project-detection
[dev] 
  command = "yarn start" # Command to start your dev server
  port = 3001 # Port that the dev server will be listening on
  publish = "." # Folder with the static content for _redirect file
  
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/ 

[[redirects]]
  from = "/*"
  to = "/"
  status = 200